### ISSUE TITLE
XFS-203 DynamoDB Tables

### ISSUE THREAD

**Issue by learnuidev** [learnuidev/hello-next#10]
**Implement file metadata table structures with CDK**

- Stream specifications for metadata deletion table
- TTL configuration for automatic cleanup
- Capacity modes matching original PAY_PER_REQUEST

Technical Detail from V1

```yml
FileMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FileMetadata
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: fileId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: file-metadata-table
```
